### ISSUE TITLE
Problems with contracts/current/escrow.sol

### ISSUE THREAD

**Issue by havingfunq** [James-Sangalli/Solidity-Contract-Examples#1]
I was using the mentioned script, and I may have uncovered an error. The script throws() in the buyerOrSellerOnly modifier, when the buyer calls it. Your conditional is a little off. Will you honor a pull request?

**Comment by JamesANZ** [comment]
Sure, thanks for spotting!

**Comment by Isan-Rivkin** [comment]
Hi i think i spotted a small change that should be made, the throw is deprecated, better replacing them with require() or revert()
