### ISSUE TITLE
Error: JSON Parse error

### ISSUE THREAD

**Issue by raky35** [James-Sangalli/Solidity-Contract-Examples#2]
Hello James , Thanks for sharing knowledge , i am trying to run your contract in Remix ide and struggling get it working. I am afraid i am getting error  in pragma solidity ^0.4.11; I have tried to pass the address hardcoded but no luck .

While invoking  deploy function with addresses as parameter i am getting error ,  i have tried to add the local remix address  with /without different braces/both cases letters/with/without comma but no luck , please advice what i am doing wrong - i have chosen 1st address of remix for contract and 2nd address for buying and 3rd contract for seller.

 {'0X14723A09ACFF6D2A60DCDF7AA4AFF308FDDC160C' , '0X4B0897B0513FDC7C541B6D9D7E929C4E5364D2DB'} 

![screen shot 2018-05-21 at 10 46 50](https://user-images.githubusercontent.com/7769590/40302670-c600ad08-5ce7-11e8-83f2-be5270042f9b.png)

Hope for help.

Kind Regards
raky

**Comment by JamesANZ** [comment]
Solved via email, needed checksum, double quotes and removal of curly braces

**Comment by raky35** [comment]
Thanks James , the input should be submitted in double quotes.   Cheers raky
